esphome:
  name: $name
  friendly_name: $friendly_name
  name_add_mac_suffix: true
  project:
    name: $project_name
    version: $project_version
  on_boot:
    - priority: 800.0
      then:
        - text_sensor.template.publish:
            id: device_id
            state: !lambda return get_mac_address();
        - text_sensor.template.publish:
            id: project_version
            state: !lambda return ESPHOME_PROJECT_VERSION;

esp8266:
  board: nodemcuv2
  restore_from_flash: true

substitutions:
  status_led_inverted: "true"

text_sensor:
  - platform: template
    name: Device ID
    id: device_id
    entity_category: diagnostic
    update_interval: never
  - platform: version
    name: ESPHome Version
    hide_timestamp: true
  - platform: template
    name: Project version
    id: project_version
    entity_category: diagnostic
    update_interval: never    
    
sensor:
  - platform: uptime
    name: Uptime
    id: uptime_sensor
    entity_category: diagnostic
    
button:
  - platform: restart
    name: Restart
    entity_category: config

#### 
# OTA UPDATES
# Enables over-the-air updates
# more: https://esphome.io/components/ota.html
ota:
  - platform: esphome
    id: konnected_ota
