script:
  - id: pc_warn
    then:
      - button.press: pre_close_warning

secplus_gdo:
  id: gdo_blaq
  input_gdo_pin: ${uart_rx_pin}
  output_gdo_pin: ${uart_tx_pin}

light:
  - platform: secplus_gdo
    name: $garage_light_name
    secplus_gdo_id: gdo_blaq
    id: gdo_light

cover:
  - platform: secplus_gdo
    name: $garage_door_cover_name
    secplus_gdo_id: gdo_blaq
    id: gdo_door
    pre_close_warning_duration: $garage_door_close_warning_duration
    pre_close_warning_start:
      - script.execute:
          id: pc_warn
    pre_close_warning_end:
      - script.stop: pc_warn
      - light.turn_off: warning_led

sensor:
  - platform: secplus_gdo
    secplus_gdo_id: gdo_blaq
    id: gdo_openings
    type: openings
    name: $garage_openings_name
    unit_of_measurement: openings
    icon: mdi:open-in-app

lock:
  - platform: secplus_gdo
    id: gdo_lock_remotes
    secplus_gdo_id: gdo_blaq
    name: $garage_lock_name

binary_sensor:
  - platform: secplus_gdo
    name: $garage_motion_name
    id: gdo_motion
    secplus_gdo_id: gdo_blaq
    device_class: motion
    type: motion
  - platform: secplus_gdo
    name: $garage_obstruction_name
    id: gdo_obst
    secplus_gdo_id: gdo_blaq
    device_class: problem
    type: obstruction
  - platform: secplus_gdo
    name: $garage_motor_name
    id: gdo_motor
    secplus_gdo_id: gdo_blaq
    device_class: running
    type: motor
  - platform: secplus_gdo
    name: $garage_button_name
    id: gdo_button
    secplus_gdo_id: gdo_blaq
    type: button
  - platform: secplus_gdo
    name: $garage_sync_name
    id: gdo_synced
    secplus_gdo_id: gdo_blaq
    type: sync
    device_class: connectivity

switch:
  - platform: secplus_gdo
    id: gdo_learn
    type: learn
    secplus_gdo_id: gdo_blaq
    name: Learn
    icon: mdi:plus-box
  - platform: secplus_gdo
    id: gdo_toggle_only
    type: toggle_only
    secplus_gdo_id: gdo_blaq
    name: Toggle Only
    icon: mdi:plus-box
    entity_category: config

select:
  - platform: secplus_gdo
    id: gdo_protocol
    secplus_gdo_id: gdo_blaq
    name: Security+ protocol
    icon: mdi:settings
    entity_category: config

button:
  - platform: factory_reset
    id: hard_reset
    name: Factory Reset
    entity_category: config
  - platform: template
    id: reset_door_timings
    name: Reset door timings
    entity_category: config
    on_press:
      - number.set:
          id: gdo_open_duration
          value: 0
      - number.set:
          id: gdo_close_duration
          value: 0
      - button.press:
          id: restart_button
  - platform: template
    id: resync
    name: Re-sync
    entity_category: config
    on_press:
      - if:
          condition:
            lambda: 'return id(gdo_client_id).state;'
          then:
            - number.increment:
                id: gdo_client_id
          else:
            - number.set:
                id: gdo_client_id
                value: 0x667
      - number.set:
          id: gdo_rolling_code
          value: 0
      - button.press:
          id: restart_button

number:
  - platform: secplus_gdo
    name: Opening duration
    secplus_gdo_id: gdo_blaq
    entity_category: config
    id: gdo_open_duration
    type: open_duration
    unit_of_measurement: "ms"
    internal: true

  - platform: secplus_gdo
    name: Closing duration
    secplus_gdo_id: gdo_blaq
    entity_category: config
    id: gdo_close_duration
    type: close_duration
    unit_of_measurement: "ms"
    internal: true

  - platform: secplus_gdo
    name: Client ID
    secplus_gdo_id: gdo_blaq
    entity_category: config
    id: gdo_client_id
    type: client_id
    mode: box
    internal: true

  - platform: secplus_gdo
    name: Rolling Code
    secplus_gdo_id: gdo_blaq
    entity_category: config
    id: gdo_rolling_code
    type: rolling_code
    mode: box
    internal: true

wifi:
  on_connect:
    lambda: id(gdo_blaq).start_gdo();
